# Jacobi迭代解法

**线性代数公式:** $x^{(k+1)} =D^{-1} b-D^{-1} L x^{(k)}-D^{-1} R x^{(k)}$


$\alpha = [[a_{11}],
           [a_{22}],
           [a_{33}],
           ...,
           [a_{nn}]
           ]^T$

$\alpha * x = b - Ax + \alpha * x$

$ x_{k+1} = (b/\alpha) - (A/\alpha) x_k +  x_{k}$

In [16]:
import numpy as np


def ln(x: np.ndarray, newX: np.ndarray):
    return np.max(np.abs(newX - x))


def l2(x: np.ndarray, newX: np.ndarray):
    return np.sqrt(np.sum(np.square(newX - x)))


def jacobi(A, x, b, distance, e):
    a = np.diagonal(A).reshape(-1,1)
    b = b/a
    A = A/a

    result = []
    while True:
        newX = b - np.dot(A, x) + x
        if distance(x, newX) < e:
            break
        x = newX
        result.append(x)
    return result

In [17]:
A = np.array([[5, 2, 3], [-1, 4, 2], [2, -3, 10]])
b = np.array([[-12], [20],[3]])
x0 = [[0], [0], [0]]
distance = ln
e = 1e-4

xlist = jacobi(A, x0, b, distance, e)
xlist

[array([[-2.4],
        [ 5. ],
        [ 0.3]]),
 array([[-4.58],
        [ 4.25],
        [ 2.28]]),
 array([[-5.468],
        [ 2.715],
        [ 2.491]]),
 array([[-4.9806],
        [ 2.3875],
        [ 2.2081]]),
 array([[-4.67986],
        [ 2.6508 ],
        [ 2.01237]]),
 array([[-4.667742],
        [ 2.82385 ],
        [ 2.031212]]),
 array([[-4.7482672],
        [ 2.8174585],
        [ 2.0807034]]),
 array([[-4.77540544],
        [ 2.7725815 ],
        [ 2.09489099]]),
 array([[-4.76596719],
        [ 2.75870315],
        [ 2.08685554]]),
 array([[-4.75559458],
        [ 2.76508043],
        [ 2.08080438]]),
 array([[-4.7545148 ],
        [ 2.77069916],
        [ 2.08064305]]),
 array([[-4.75666549],
        [ 2.77104978],
        [ 2.08211271]]),
 array([[-4.75768754],
        [ 2.76977727],
        [ 2.08264803]]),
 array([[-4.75749973],
        [ 2.7692541 ],
        [ 2.08247069]]),
 array([[-4.75718405],
        [ 2.76938972],
        [ 2.08227618]]),
 array([[-4.7571215

In [9]:
A = np.array([[5, 2, 3], [-1, 4, 2], [2, -3, 10]])
b = np.array([[-12], [20],[3]])
x = np.linalg.solve(A, b)
x

array([[-4.75720165],
       [ 2.76954733],
       [ 2.08230453]])

## 对角矩阵相关补充

+ np.diagonal(A): 提取对角线元素
+ np.diag([1,2,3,4]): 根据列表生成一个对角矩阵

In [11]:
np.diag(np.diagonal(A))

array([[ 5,  0,  0],
       [ 0,  4,  0],
       [ 0,  0, 10]])

In [14]:
a = np.diagonal(A).reshape(-1,1)

In [15]:
a * a


array([[ 25],
       [ 16],
       [100]])