In [1]:
import numpy as np

In [2]:
A = np.array([[2, 2, 3],
              [4, 7, 7],
              [-2, 4, 5]])
n = A.shape[0]
n

3

In [3]:
L = np.diag(np.ones(n))
L

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 矩阵取值

In [9]:
# 取行向量
print(L[0])

# 取单个值
print(L[0][1])

# 取列向量
print(L[:, [1]])

[1. 0. 0.]
0.0
[[0.]
 [1.]
 [0.]]


In [4]:
U = np.zeros(A.shape)
U

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
print(np.zeros(n))

[0. 0. 0.]


In [14]:
for i in range(n):
    # 更新第i行U
    dU = np.zeros(n)
    for j in range(i):
        dU += L[i][j] * U[j]
    U[i] = A[i] - dU

    # 更新第i列L
    dL = np.zeros(n).reshape(-1, 1)
    for j in range(i):
        dL += U[j][i] * L[:, [j]]
    L[:, [i]] = (A[:, [i]] - dL) / U[i][i]

print(L)
print(U)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  2.  1.]]
[[2. 2. 3.]
 [0. 3. 1.]
 [0. 0. 6.]]


In [15]:
print(np.dot(L, U))

[[ 2.  2.  3.]
 [ 4.  7.  7.]
 [-2.  4.  5.]]


# 封装LU分解

In [17]:
def LU(A):
    n = A.shape[0]
    L = np.diag(np.ones(n))
    U = np.zeros(A.shape)
    for i in range(n):
        # 更新第i行U
        dU = np.zeros(n)
        for j in range(i):
            dU += L[i][j] * U[j]
        U[i] = A[i] - dU

        # 更新第i列L
        dL = np.zeros(n).reshape(-1, 1)
        for j in range(i):
            dL += U[j][i] * L[:, [j]]
        L[:, [i]] = (A[:, [i]] - dL) / U[i][i]
    print(np.dot(L, U) == A)
    return L, U

In [18]:
LU(A)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


(array([[ 1.,  0.,  0.],
        [ 2.,  1.,  0.],
        [-1.,  2.,  1.]]),
 array([[2., 2., 3.],
        [0., 3., 1.],
        [0., 0., 6.]]))

# 为矩阵列向量赋值

In [10]:
test = np.diag(np.ones(n))
test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
test[:, [1]] = np.array([0, 0, 0]).reshape(-1, 1)
test

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

**用行向量为列向量赋值, 报错**

In [12]:
test[:, [1]] = np.array([0, 0, 0])
test


ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (3,1)